require defaultTheme
Fixes error:

% npm start
...
> negative-stablecoin@0.1.0 watch:tailwind /Users/elliotlee/xpring-eng/negative-stablecoin
> postcss -w src/css/tailwind.css -o src/css/tailwind.out.css

ReferenceError: defaultTheme is not defined
    at Object.<anonymous> (/Users/elliotlee/xpring-eng/negative-stablecoin/tailwind.config.js:7:56)
...